import { Injectable } from '@angular/core';
import { Item } from './shared/item.model';

@Injectable({
  providedIn: 'root'
})
export class ItemService {
  items : Item[] = [
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    2137,
    17,
    'producent'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent2'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent3'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent4'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    2137,
    17,
    'producent'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent2'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent3'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent4'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    2137,
    17,
    'producent'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent2'),
    /* new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent3'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent4'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    2137,
    17,
    'producent'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent2'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent3'),
    new Item ('Nazwa',
    'Opis',
    'https://img.freepik.com/premium-zdjecie/osiol-z-bialym-tlem-i-bialym-tlem_873925-22917.jpg',
    '500g',
    50,
    50,
    'producent4'),   */
]
  constructor() { }
}
